Repository MOVIEBOOKIE/MOVIEBOOKIE_BE, pull requests merged in 2025-07, with the labels that each got.

#160 [FIX] 이벤트 신청 시 달성률 관련 오류 수정
  build.gradle
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
  src/main/java/project/luckybooky/global/config/AppConfig.java
Labels: 🐞 BugFix

#166 [CHORE] 알림 전송 시 알림 테이블에 알림 내역 저장되도록 수정, 알림 조회
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
  src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
  src/main/java/project/luckybooky/domain/notification/dto/request/NotificationRequestDTO.java
  src/main/java/project/luckybooky/domain/notification/dto/response/NotificationResponseDTO.java
  src/main/java/project/luckybooky/domain/notification/dto/response/SendNotificationResponseDTO.java
  src/main/java/project/luckybooky/domain/notification/entity/NotificationInfo.java
  src/main/java/project/luckybooky/domain/notification/listener/HostNotificationListener.java
  src/main/java/project/luckybooky/domain/notification/listener/ParticipantNotificationListener.java
  src/main/java/project/luckybooky/domain/notification/repository/NotificationRepository.java
  src/main/java/project/luckybooky/domain/notification/service/NotificationService.java
  src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
Labels: 📬 API, ✏️ Chore

#175 [FEATURE] 유저 로그아웃, 회원탈퇴 기능 구현
  src/main/java/project/luckybooky/domain/user/controller/AuthController.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/domain/user/service/AuthService.java
Labels: 📬 API, ✏️ Chore, ✨ Feature

#181 [REFACTOR] 내가 주최/신청한 이벤트 목록 조회 로직 수정
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/participation/controller/ParticipationController.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
Labels: 📬 API, 🔨 Refactor

#184 [REFACTOR] 기능 QA 반영
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/user/controller/AuthController.java
Labels: 📃 Docs, 🔨 Refactor

#186 [FIX] 로그인, 인증번호 발송 앤드포인트 Security 허용
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#187 [REFACTOR] 기능 QA 반영 (이벤트탭 리스트 조회 기준 수정, 이벤트 태그 추가)
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/entity/Event.java
  src/main/java/project/luckybooky/domain/event/entity/type/EventStatus.java
  src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
Labels: 🔨 Refactor

#190 [FIX] 기능 QA 반영
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
  src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
  src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
  src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
  src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/project/luckybooky/global/redis/RedisCertificationCache.java
Labels: 🐞 BugFix, ✏️ Chore, 🌱 Enhance
