Repository MOVIEBOOKIE/MOVIEBOOKIE_BE, pull requests merged in 2025-05, with the labels that each got.

#13 [INIT] 이벤트 도메인 생성
  src/main/java/project/luckybooky/domain/category/entity/Category.java
  src/main/java/project/luckybooky/domain/category/repository/CategoryRepository.java
  src/main/java/project/luckybooky/domain/category/repository/init/CategoryInitializer.java
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/entity/Event.java
  src/main/java/project/luckybooky/domain/event/entity/type/EventStatus.java
  src/main/java/project/luckybooky/domain/event/entity/type/HostEventStatus.java
  src/main/java/project/luckybooky/domain/event/entity/type/ParticipantEventStatus.java
  src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/location/entity/Location.java
  src/main/java/project/luckybooky/domain/location/repository/LocationRepository.java
  src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
  src/main/java/project/luckybooky/domain/participation/entity/Participation.java
  src/main/java/project/luckybooky/domain/participation/entity/type/ParticipateRole.java
  src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/global/entity/BaseEntity.java
  src/main/java/project/luckybooky/global/util/DummyDataInit.java
Labels: ✨ Feature, ⚙ Setting

#15 [INIT] user 도메인 세팅 + 유저 더미데이터 생성
  src/main/java/project/luckybooky/domain/user/entity/ContentCategory.java
  src/main/java/project/luckybooky/domain/user/entity/GroupType.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/domain/user/entity/UserType.java
  src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
Labels: 💾 Database, ⚙ Setting

#17 [FEAT] 사용자 유형 검사 + 유저 테이블 컬럼 추가
  src/main/java/project/luckybooky/domain/user/controller/AuthController.java
  src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
  src/main/java/project/luckybooky/domain/user/converter/UserConverter.java
  src/main/java/project/luckybooky/domain/user/dto/request/UserTypeAssignRequest.java
  src/main/java/project/luckybooky/domain/user/dto/response/UserResponseDTO.java
  src/main/java/project/luckybooky/domain/user/dto/response/UserTypeAssignResponse.java
  src/main/java/project/luckybooky/domain/user/dto/response/UserTypeResultDTO.java
  src/main/java/project/luckybooky/domain/user/entity/Step1Question.java
  src/main/java/project/luckybooky/domain/user/entity/Step2Question.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/domain/user/entity/UserType.java
  src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
  src/main/java/project/luckybooky/domain/user/service/AuthService.java
  src/main/java/project/luckybooky/domain/user/service/UserTypeService.java
  src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
Labels: 📬 API, 💾 Database, ✨ Feature

#21 [INIT] #19: 레디스 사용을 위한 도커 세팅
  docker-compose.yml
Labels: ⚙ Setting

#28 [SETTING] 영화관 리스트 DB 저장
  src/main/java/project/luckybooky/domain/location/entity/Location.java
  src/main/java/project/luckybooky/domain/location/entity/type/LocationKeyword.java
  src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
Labels: ⚙ Setting

#30 [FEATURE] 카테고리별 이벤트 조회 API 구현
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/entity/Event.java
  src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
Labels: 📬 API, ✨ Feature

#32 [FEATURE] 이벤트 상세 조회 API 구현
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
Labels: 📬 API, ✨ Feature

#34 [FEATURE] 이벤트 생성 시 이벤트 특성에 맞는 영화관 목록 조회 추천 API 구현
  src/main/java/project/luckybooky/domain/category/repository/init/CategoryInitializer.java
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/location/controller/LocationController.java
  src/main/java/project/luckybooky/domain/location/converter/LocationConverter.java
  src/main/java/project/luckybooky/domain/location/dto/request/LocationRequest.java
  src/main/java/project/luckybooky/domain/location/dto/response/LocationResponse.java
  src/main/java/project/luckybooky/domain/location/entity/Location.java
  src/main/java/project/luckybooky/domain/location/entity/type/AvailableMediaType.java
  src/main/java/project/luckybooky/domain/location/repository/LocationRepository.java
  src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
  src/main/java/project/luckybooky/domain/location/service/LocationService.java
Labels: 📬 API, ✨ Feature

#41 [refactor] #40: 유저 더미데이터 임시 토큰 발급
  src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
Labels: ✏️ Chore, 🔨 Refactor

#36 [FEATURE] 이벤트 검색 API 구현
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/location/converter/LocationConverter.java
  src/main/java/project/luckybooky/domain/location/dto/response/LocationResponse.java
Labels: 📬 API, ✨ Feature

#46 [FEATURE] 상영 완료 처리 & 사용자 피드백 수집 기능 구현
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/entity/Event.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/event/util/EventConstants.java
  src/main/java/project/luckybooky/domain/feedback/controller/FeedbackController.java
  src/main/java/project/luckybooky/domain/feedback/converter/FeedbackConverter.java
  src/main/java/project/luckybooky/domain/feedback/dto/request/FeedbackRequest.java
  src/main/java/project/luckybooky/domain/feedback/dto/response/FeedbackResponse.java
  src/main/java/project/luckybooky/domain/feedback/entity/Feedback.java
  src/main/java/project/luckybooky/domain/feedback/entity/type/NegativeFeedback.java
  src/main/java/project/luckybooky/domain/feedback/entity/type/PositiveFeedback.java
  src/main/java/project/luckybooky/domain/feedback/repository/FeedbackRepository.java
  src/main/java/project/luckybooky/domain/feedback/service/FeedbackService.java
  src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/domain/user/service/UserTypeService.java
Labels: 📬 API, ✨ Feature

#55 [FEAT] 마이페이지 api, 토큰 재발급 api 구현
  src/main/java/project/luckybooky/domain/certification/email/controller/EmailController.java
  src/main/java/project/luckybooky/domain/certification/sms/controller/SmsController.java
  src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
  src/main/java/project/luckybooky/domain/user/controller/AuthController.java
  src/main/java/project/luckybooky/domain/user/controller/MypageController.java
  src/main/java/project/luckybooky/domain/user/controller/UserTypeController.java
  src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
  src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
  src/main/java/project/luckybooky/domain/user/dto/response/ReissueResultDTO.java
  src/main/java/project/luckybooky/domain/user/service/AuthService.java
  src/main/java/project/luckybooky/domain/user/service/MypageService.java
  src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
  src/main/java/project/luckybooky/global/jwt/JwtUtil.java
  src/main/java/project/luckybooky/global/jwt/TokenService.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#64 [SETTING] 이벤트 더미데이터 생성
  src/main/java/project/luckybooky/domain/category/repository/init/CategoryInitializer.java
  src/main/java/project/luckybooky/domain/event/repository/init/EventInitializer.java
  src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
  src/main/java/project/luckybooky/domain/user/repository/init/UserInitializer.java
  src/main/java/project/luckybooky/global/util/DummyDataInitForDev.java
Labels: ✨ Feature, ⚙ Setting

#73 [FEATURE] 티켓 목록 조회 API 구현
  src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
  src/main/java/project/luckybooky/domain/ticket/converter/TicketConverter.java
  src/main/java/project/luckybooky/domain/ticket/dto/response/TicketResponse.java
  src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
  src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
  src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
Labels: 📬 API, ✨ Feature

#82 [FIX] 영화관 Location 데이터 이미지 URL 변경
  src/main/java/project/luckybooky/domain/location/repository/init/LocationInitializer.java
Labels: 🐞 BugFix

#84 [FEAT] 호스트 이벤트 상태별 푸시 알림 기능 구현
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/notification/controller/NotificationController.java
  src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
  src/main/java/project/luckybooky/domain/notification/event/HostNotificationEvent.java
  src/main/java/project/luckybooky/domain/notification/listener/HostNotificationListener.java
  src/main/java/project/luckybooky/domain/notification/service/NotificationService.java
  src/main/java/project/luckybooky/domain/notification/type/HostNotificationType.java
  src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
  src/main/java/project/luckybooky/global/config/FcmConfig.java
  src/main/java/project/luckybooky/global/config/WebConfig.java
Labels: 📬 API, ✨ Feature

#91 [CHORE] 마이페이지 조회 응답값 수정, 줄바꿈 삭제
  src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
  src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
  src/main/java/project/luckybooky/domain/user/converter/MypageConverter.java
  src/main/java/project/luckybooky/domain/user/dto/response/MypageResponseDTO.java
  src/main/java/project/luckybooky/domain/user/entity/User.java
  src/main/java/project/luckybooky/domain/user/service/MypageService.java
Labels: ✏️ Chore

#105 [REFACTOR] 이벤트 카테고리별 목록 조회 시 총 페이지 수 데이터 추가
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
Labels: 📬 API, 🔨 Refactor

#109 [REFACTOR] 사용자 역할 처리 로직 개선 & 미참여자 네이밍 수정
  src/main/java/project/luckybooky/domain/event/service/EventService.java
Labels: 🔨 Refactor

#111 [REFACTOR] 이벤트의 '대관 진행 중' 상태 제거
  src/main/java/project/luckybooky/domain/event/entity/Event.java
  src/main/java/project/luckybooky/domain/event/entity/type/EventStatus.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipationService.java
Labels: 🔨 Refactor

#113 [FEATURE] '티켓으로 이동' API 생성
  src/main/java/project/luckybooky/domain/ticket/controller/TicketController.java
  src/main/java/project/luckybooky/domain/ticket/converter/TicketConverter.java
  src/main/java/project/luckybooky/domain/ticket/entity/Ticket.java
  src/main/java/project/luckybooky/domain/ticket/repository/TicketRepository.java
  src/main/java/project/luckybooky/domain/ticket/service/TicketService.java
Labels: 📬 API, ✨ Feature

#121 [REFACTOR] 이벤트 검색 페이지네이션 응답에 총 페이지 수 추가
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/converter/EventConverter.java
  src/main/java/project/luckybooky/domain/event/dto/response/EventResponse.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
Labels: 🔨 Refactor

#125 [CHORE] 이벤트 상세 조회 비로그인 유저 허용
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
Labels: ✏️ Chore, 🌱 Enhance

#126 [FEAT] 디스코드 웹훅 연동(대관 신청 정보)
  src/main/java/project/luckybooky/domain/admin/converter/WebhookConverter.java
  src/main/java/project/luckybooky/domain/admin/dto/ParticipantInfo.java
  src/main/java/project/luckybooky/domain/admin/dto/VenueRequestWebhookDTO.java
  src/main/java/project/luckybooky/domain/admin/event/VenueRequestWebhookEvent.java
  src/main/java/project/luckybooky/domain/admin/listener/VenueRequestWebhookListener.java
  src/main/java/project/luckybooky/domain/admin/service/WebhookService.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
Labels: ✏️ Chore, 🌱 Enhance, ✨ Feature

#129 [CHORE] 이벤트 상세 조회 비로그인 유저 접근 허용
  src/main/java/project/luckybooky/domain/event/controller/EventController.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
Labels: ✏️ Chore, 🌱 Enhance

#130 [CHORE] 로그인 리다이렉트 수정, 알림 응답값 포멧 수정
  src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
  src/main/java/project/luckybooky/domain/user/repository/UserRepository.java
  src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: ✏️ Chore, 🌱 Enhance
