Repository MOVIEBOOKIE/MOVIEBOOKIE_BE, pull requests merged in 2025-08, with the labels that each got.

#200 [CHORE] 주최자, 참여자 상영 완료 후기 요청 알림 문구 수정
  src/main/java/project/luckybooky/domain/notification/type/HostNotificationType.java
  src/main/java/project/luckybooky/domain/notification/type/ParticipantNotificationType.java
Labels: ✏️ Chore

#203 [REFACTOR] 참여자 정보 확인 로직 수정
  src/main/java/project/luckybooky/domain/participation/controller/ParticipantInfoController.java
  src/main/java/project/luckybooky/domain/participation/dto/ParticipantInfoResult.java
  src/main/java/project/luckybooky/domain/participation/repository/ParticipationRepository.java
  src/main/java/project/luckybooky/domain/participation/service/ParticipantInfoService.java
  src/main/java/project/luckybooky/global/oauth/handler/AuthFailureHandler.java
  src/main/resources/templates/participants.html
Labels: ✏️ Chore, 🌱 Enhance, 🔨 Refactor

#206 [FIX] 링크 생성 오류 수정
  src/main/java/project/luckybooky/domain/notification/converter/NotificationConverter.java
  src/main/java/project/luckybooky/domain/notification/service/MailTemplateService.java
Labels: 🐞 BugFix

#210 [FEAT] 네임드락을 활용하여 일정 겹치는 이벤트 동시 생성 방지
  src/main/java/project/luckybooky/domain/event/repository/EventRepository.java
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/global/apiPayload/error/dto/ErrorCode.java
Labels: ✨ Feature

#219 [CHORE] 5차 기능 QA 수정사항 반영
  src/main/java/project/luckybooky/domain/event/service/EventService.java
  src/main/java/project/luckybooky/domain/notification/service/MailTemplateService.java
  src/main/java/project/luckybooky/domain/notification/type/HostNotificationType.java
  src/main/java/project/luckybooky/domain/notification/type/ParticipantNotificationType.java
  src/main/java/project/luckybooky/domain/participation/controller/ParticipantInfoController.java
  src/main/java/project/luckybooky/domain/participation/service/MailLinkTokenService.java
  src/main/java/project/luckybooky/domain/secureMail/service/LinkCryptoService.java
  src/main/java/project/luckybooky/domain/secureMail/service/MailLinkTokenService.java
  src/main/java/project/luckybooky/global/apiPayload/error/handler/GlobalExceptionHandler.java
  src/main/java/project/luckybooky/global/config/SecurityConfig.java
  src/main/java/project/luckybooky/global/config/WebConfig.java
  src/main/java/project/luckybooky/global/config/WebMvcConfig.java
  src/main/java/project/luckybooky/global/security/MailLinkAuthFilter.java
  src/main/java/project/luckybooky/global/security/MailLinkTokenInterceptor.java
  src/main/resources/templates/email-certification.html
  src/main/resources/templates/error/404.html
Labels: 🐞 BugFix, ✏️ Chore, 🌱 Enhance

#227 [FIX] 재로그인 시 401 에러 수정
  src/main/java/project/luckybooky/domain/user/service/AuthService.java
  src/main/java/project/luckybooky/global/jwt/JwtAuthenticationFilter.java
  src/main/java/project/luckybooky/global/jwt/JwtUtil.java
Labels: 🐞 BugFix

#229 [FIX] #228: 재로그인 시 redis에 저장된 기존 토큰을 삭제하고 재할당하도록 수정
  src/main/java/project/luckybooky/domain/user/service/AuthService.java
  src/main/java/project/luckybooky/global/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: 🐞 BugFix

#245 [FIX] #244: eventTitle-> mediaTitle로 수정
  src/main/resources/templates/venue_confirmed.html
Labels: 🐞 BugFix
